# Generated by Django 6.0.2 on 2026-03-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_event_t_31d1af_idx',
            old_name='notif_event_idemp_idx',
        ),
    ]
