# Generated by Django 6.0.3 on 2026-03-27 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notif_event_idemp_idx_notificatio_event_t_31d1af_idx'),
        ('reviews', '0002_alter_reviewassignment_token'),
        ('submissions', '0003_remove_draft_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('submission_submitted', 'Submission Submitted'), ('status_changed', 'Status Changed'), ('reviewer_invited', 'Reviewer Invited'), ('reviewer_accepted', 'Reviewer Accepted'), ('reviewer_declined', 'Reviewer Declined'), ('review_submitted', 'Review Submitted'), ('revision_requested', 'Revision Requested'), ('submission_accepted', 'Submission Accepted'), ('submission_rejected', 'Submission Rejected'), ('submission_published', 'Submission Published'), ('review_reminder', 'Review Reminder'), ('email_verification', 'Email Verification')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReviewerRecognitionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500)),
                ('author_full_name', models.CharField(max_length=255)),
                ('reviewer_full_name', models.CharField(max_length=255)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_recognition_certificates', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_certificate', to='reviews.review')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_recognition_certificates', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_certificates', to='submissions.submission')),
            ],
            options={
                'db_table': 'notifications_reviewer_recognition_certificate',
                'ordering': ['-issued_at'],
            },
        ),
    ]
