# Generated by Django 6.0.3 on 2026-03-28 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_event_type_and_more'),
        ('submissions', '0005_journalissue_publication_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPublicationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500)),
                ('author_full_name', models.CharField(max_length=255)),
                ('issue_title', models.CharField(max_length=255)),
                ('volume', models.PositiveIntegerField()),
                ('issue_number', models.PositiveIntegerField()),
                ('publication_year', models.PositiveIntegerField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_publication_certificates', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_journal_certificates', to='submissions.journalissue')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_publication_certificates', to='submissions.submission')),
            ],
            options={
                'db_table': 'notifications_journal_publication_certificate',
                'ordering': ['-issued_at'],
                'unique_together': {('issue', 'submission', 'author')},
            },
        ),
    ]
