# Generated by Django 6.0.4 on 2026-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_journalpublicationcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('submission_submitted', 'Submission Submitted'), ('status_changed', 'Status Changed'), ('reviewer_invited', 'Reviewer Invited'), ('reviewer_accepted', 'Reviewer Accepted'), ('reviewer_declined', 'Reviewer Declined'), ('review_submitted', 'Review Submitted'), ('revision_requested', 'Revision Requested'), ('submission_accepted', 'Submission Accepted'), ('submission_rejected', 'Submission Rejected'), ('submission_published', 'Submission Published'), ('review_reminder', 'Review Reminder'), ('email_verification', 'Email Verification'), ('profile_updated', 'Profile Updated')], max_length=50),
        ),
    ]
