# Generated by Django 5.2.17 on 2026-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_submitted", "Submission Submitted"),
                    ("status_changed", "Status Changed"),
                    ("reviewer_invited", "Reviewer Invited"),
                    ("reviewer_accepted", "Reviewer Accepted"),
                    ("reviewer_declined", "Reviewer Declined"),
                    ("review_submitted", "Review Submitted"),
                    ("revision_requested", "Revision Requested"),
                    ("submission_accepted", "Submission Accepted"),
                    ("submission_rejected", "Submission Rejected"),
                    ("submission_published", "Submission Published"),
                    ("review_reminder", "Review Reminder"),
                    ("email_verification", "Email Verification"),
                    ("profile_updated", "Profile Updated"),
                    ("reviewer_approved", "Reviewer Approved"),
                    ("editor_approved", "Editor Approved"),
                ],
                max_length=50,
            ),
        ),
    ]
