services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ejournal
      POSTGRES_USER: ejournal
      POSTGRES_PASSWORD: ejournal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ejournal"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py seed_db &&
             gunicorn --bind 0.0.0.0:8000 -c gunicorn.conf.py ejournal.wsgi:application"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: ejournal.settings.dev
      DATABASE_URL: postgres://ejournal:ejournal@db:5432/ejournal
      CELERY_BROKER_URL: redis://redis:6379/0
      USE_S3_STORAGE: "false"
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A ejournal worker -l info
    volumes:
      - .:/app
      - ./media:/app/media
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: ejournal.settings.dev
      DATABASE_URL: postgres://ejournal:ejournal@db:5432/ejournal
      CELERY_BROKER_URL: redis://redis:6379/0
      USE_S3_STORAGE: "false"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # front:
  #   image: node:18-bullseye
  #   working_dir: /app
  #   volumes:
  #     - ../ejournal-front:/app
  #     - /app/node_modules
  #   env_file: ../ejournal-front/.env
  #   environment:
  #     # Ensure frontend can reach backend service by service name 'web'
  #     VITE_CONTACT_ENDPOINT: http://web:8000/api/certificates/contact/
  #     VITE_CONTACT_TO_EMAIL: contact@ditechasia.org
  #   command: sh -c "npm ci --prefer-offline --no-audit --no-fund && npm run dev -- --host 0.0.0.0"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     web:
  #       condition: service_healthy

volumes:
  postgres_data:
