# Generated by Django 6.0.3 on 2026-03-28 10:29

import django.db.models.deletion
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='issue_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('volume', models.PositiveIntegerField()),
                ('issue_number', models.PositiveIntegerField()),
                ('publication_year', models.PositiveIntegerField()),
                ('full_issue_pdf', models.FileField(blank=True, null=True, upload_to=submissions.models.issue_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'submissions_journal_issue',
                'ordering': ['-publication_year', '-volume', '-issue_number'],
                'unique_together': {('volume', 'issue_number', 'publication_year')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='submissions.journalissue'),
        ),
    ]
