# Generated by Django 6.0.3 on 2026-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_issue_order_submission_page_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
