# Generated by Django 5.2.6 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_journalissue_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="doi",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="doi_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("registered", "Registered"), ("failed", "Failed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
