# Generated by Django 5.2.17 on 2026-09-16 05:19

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_submission_doi_and_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="ai_use_disclosure",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="article_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("original_research", "Original Research Article"),
                    ("review_article", "Review Article"),
                    ("systematic_review", "Systematic Literature Review"),
                    ("case_study", "Case Study"),
                    ("technical_note", "Technical Note"),
                    ("short_communication", "Short Communication"),
                    ("perspective", "Perspective/Policy Paper"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="co_authors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="submission",
            name="conflict_of_interest",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="cover_letter_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=submissions.models.cover_letter_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="cover_letter_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="data_availability_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="english_abstract",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="english_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="submission",
            name="english_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="submission",
            name="ethics_approval_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="ethics_approval_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=submissions.models.ethics_approval_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="funding_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("uz", "Uzbek")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="manuscript_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="references",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="running_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="submission",
            name="title_page",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=submissions.models.title_page_upload_path,
            ),
        ),
    ]
