# Generated by Django 5.2.17 on 2026-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0007_submission_ai_use_disclosure_submission_article_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("screening", "Screening"),
                    ("desk_rejected", "Desk Rejected"),
                    ("under_review", "Under Review"),
                    ("revision_required", "Revision Required"),
                    ("resubmitted", "Resubmitted"),
                    ("decision_pending", "Decision Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
