# Generated by Django 4.2.11 on 2026-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('expertise', models.JSONField(default=list, help_text='List of expertise tags')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='editorial_board/')),
                ('role', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('managing_editor', 'Managing Editor'), ('associate_editor', 'Associate Editor')], db_index=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within role')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'editorial_board_member',
                'ordering': ['role', 'order', 'name'],
            },
        ),
    ]
