# Generated by Django 6.0.2 on 2026-03-01 12:03

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='token',
            field=models.CharField(default=reviews.models.generate_invite_token, max_length=64, unique=True),
        ),
    ]
