# Generated by Django 5.2.17 on 2026-09-16 05:19

import django.utils.timezone
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_reviewassignment_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="summary",
        ),
        migrations.AddField(
            model_name="review",
            name="comments_to_authors",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="conflict_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="conflict_of_interest",
            field=models.CharField(
                choices=[
                    ("none", "No conflict of interest"),
                    ("potential", "Potential conflict exists"),
                    ("yes", "Conflict of interest declared"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="review",
            name="discussion_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ethical_compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="literature_review",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="methodology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="originality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="overall_merit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reference_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="relevance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="results_validity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_file",
            field=models.FileField(
                blank=True, null=True, upload_to=reviews.models.review_file_upload_path
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="suggestions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="review",
            name="writing_clarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("na", "N/A"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accept", "Accept"),
                    ("minor_revision", "Accept with Minor Revisions"),
                    ("major_revision", "Major Revisions"),
                    ("reject_resubmit", "Reject and Resubmit"),
                    ("reject", "Reject"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
