# Generated by Django 6.0.2 on 2026-03-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_target__0238a6_idx',
            old_name='audit_log_target__idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_action__ff81b5_idx',
            old_name='audit_log_action__idx',
        ),
    ]
